### ISSUE TITLE
Security contact?

### ISSUE THREAD

**Issue by mogulano** [wayou/turn-issues-to-posts-action#1]
How could I report a security vulnerability?

**Comment by wayou** [comment]
Like what?

**Comment by mogulano** [comment]
Like liuwayong@gmail.com. Please check your spam box or provide an alternative email if you haven't received the one sent on November 23 GMT 0. If you have received the email, please reply with confirmation.

**Comment by wayou** [comment]
There are many, which one?

**Comment by mogulano** [comment]
The one with the subject that starts with `[SECURITY] wayou/turn-issues-to-posts-action:`.

**Comment by wayou** [comment]
There's no such one.
